# Demo is the workflow name
name: demo
on: 
  push: 
    branches: [master]
jobs:
# code is the name of the job
  code:
    runs-on: ubuntu-latest
    steps:
        - name: code-build
          run: echo " Code build."
          
    
